# Generated by Django 5.1.4 on 2025-07-07 10:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SanctionsList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('list_type', models.CharField(choices=[('OFAC', 'OFAC (US Treasury)'), ('UN', 'UN Security Council'), ('EU', 'European Union'), ('UK', 'UK HM Treasury'), ('NATIONAL', 'Lista Nacional'), ('OTHER', 'Outra')], max_length=20, verbose_name='Tipo de Lista')),
                ('source_url', models.URLField(blank=True, help_text='URL para download da lista', verbose_name='URL da Fonte')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('auto_update', models.BooleanField(default=False, verbose_name='Atualização Automática')),
                ('last_updated', models.DateTimeField(blank=True, null=True, verbose_name='Última Atualização')),
                ('update_frequency_days', models.IntegerField(default=7, verbose_name='Frequência de Atualização (dias)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
            ],
            options={
                'verbose_name': 'Lista de Sanções',
                'verbose_name_plural': 'Listas de Sanções',
                'ordering': ['list_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SanctionsEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('INDIVIDUAL', 'Pessoa Física'), ('ENTITY', 'Entidade'), ('VESSEL', 'Embarcação'), ('AIRCRAFT', 'Aeronave'), ('OTHER', 'Outro')], default='INDIVIDUAL', max_length=20, verbose_name='Tipo de Entrada')),
                ('primary_name', models.CharField(max_length=500, verbose_name='Nome Principal')),
                ('alternative_names', models.TextField(blank=True, help_text='Um nome por linha', verbose_name='Nomes Alternativos')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('place_of_birth', models.CharField(blank=True, max_length=200, verbose_name='Local de Nascimento')),
                ('nationality', models.CharField(blank=True, max_length=100, verbose_name='Nacionalidade')),
                ('passport_number', models.CharField(blank=True, max_length=50, verbose_name='Número do Passaporte')),
                ('national_id', models.CharField(blank=True, max_length=50, verbose_name='Documento Nacional')),
                ('address', models.TextField(blank=True, verbose_name='Endereço')),
                ('sanctions_program', models.CharField(blank=True, max_length=200, verbose_name='Programa de Sanções')),
                ('listing_date', models.DateField(blank=True, null=True, verbose_name='Data de Inclusão')),
                ('external_id', models.CharField(blank=True, help_text='ID na lista original', max_length=100, verbose_name='ID Externo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('sanctions_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='sanctions.sanctionslist', verbose_name='Lista de Sanções')),
            ],
            options={
                'verbose_name': 'Entrada de Sanções',
                'verbose_name_plural': 'Entradas de Sanções',
                'ordering': ['primary_name'],
            },
        ),
        migrations.CreateModel(
            name='SanctionsCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_type', models.CharField(choices=[('CUSTOMER', 'Cliente'), ('BENEFICIAL_OWNER', 'Beneficiário Final'), ('MANUAL', 'Manual')], max_length=20, verbose_name='Tipo de Verificação')),
                ('search_name', models.CharField(max_length=500, verbose_name='Nome Pesquisado')),
                ('search_document', models.CharField(blank=True, max_length=50, verbose_name='Documento Pesquisado')),
                ('search_date_of_birth', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento Pesquisada')),
                ('check_status', models.CharField(choices=[('PENDING', 'Pendente'), ('IN_PROGRESS', 'Em Andamento'), ('COMPLETED', 'Concluída'), ('FAILED', 'Falhou')], default='PENDING', max_length=20, verbose_name='Status da Verificação')),
                ('match_status', models.CharField(choices=[('NO_MATCH', 'Sem Correspondência'), ('POTENTIAL_MATCH', 'Correspondência Potencial'), ('CONFIRMED_MATCH', 'Correspondência Confirmada'), ('FALSE_POSITIVE', 'Falso Positivo')], default='NO_MATCH', max_length=20, verbose_name='Status da Correspondência')),
                ('total_matches', models.IntegerField(default=0, verbose_name='Total de Correspondências')),
                ('check_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Verificação')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('beneficial_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sanctions_checks', to='customers.beneficialowner', verbose_name='Beneficiário Final')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sanctions_checks', to='customers.customer', verbose_name='Cliente')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_sanctions_checks', to=settings.AUTH_USER_MODEL, verbose_name='Iniciado por')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sanctions_checks', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('lists_checked', models.ManyToManyField(to='sanctions.sanctionslist', verbose_name='Listas Verificadas')),
            ],
            options={
                'verbose_name': 'Verificação de Sanções',
                'verbose_name_plural': 'Verificações de Sanções',
                'ordering': ['-check_date'],
            },
        ),
        migrations.CreateModel(
            name='SanctionsMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_type', models.CharField(choices=[('EXACT_NAME', 'Nome Exato'), ('PARTIAL_NAME', 'Nome Parcial'), ('FUZZY_NAME', 'Nome Aproximado'), ('DOCUMENT', 'Documento'), ('DATE_OF_BIRTH', 'Data de Nascimento')], max_length=20, verbose_name='Tipo de Correspondência')),
                ('match_score', models.IntegerField(help_text='Score de 0-100 indicando qualidade da correspondência', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Score da Correspondência')),
                ('matched_field', models.CharField(help_text='Campo que gerou a correspondência', max_length=100, verbose_name='Campo Correspondente')),
                ('matched_value', models.CharField(max_length=500, verbose_name='Valor Correspondente')),
                ('review_status', models.CharField(choices=[('PENDING', 'Pendente'), ('CONFIRMED', 'Confirmado'), ('FALSE_POSITIVE', 'Falso Positivo'), ('NEEDS_INVESTIGATION', 'Requer Investigação')], default='PENDING', max_length=20, verbose_name='Status da Revisão')),
                ('review_notes', models.TextField(blank=True, verbose_name='Notas da Revisão')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Revisado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('sanctions_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='sanctions.sanctionscheck', verbose_name='Verificação de Sanções')),
                ('sanctions_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='sanctions.sanctionsentry', verbose_name='Entrada de Sanções')),
            ],
            options={
                'verbose_name': 'Correspondência de Sanções',
                'verbose_name_plural': 'Correspondências de Sanções',
                'ordering': ['-match_score', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sanctionsentry',
            index=models.Index(fields=['primary_name'], name='sanctions_s_primary_f48dcf_idx'),
        ),
        migrations.AddIndex(
            model_name='sanctionsentry',
            index=models.Index(fields=['passport_number'], name='sanctions_s_passpor_e58e78_idx'),
        ),
        migrations.AddIndex(
            model_name='sanctionsentry',
            index=models.Index(fields=['national_id'], name='sanctions_s_nationa_83ddaf_idx'),
        ),
        migrations.AddIndex(
            model_name='sanctionsentry',
            index=models.Index(fields=['sanctions_list', 'is_active'], name='sanctions_s_sanctio_63d154_idx'),
        ),
        migrations.AddIndex(
            model_name='sanctionscheck',
            index=models.Index(fields=['customer', 'check_date'], name='sanctions_s_custome_82c7a3_idx'),
        ),
        migrations.AddIndex(
            model_name='sanctionscheck',
            index=models.Index(fields=['beneficial_owner', 'check_date'], name='sanctions_s_benefic_b375b9_idx'),
        ),
        migrations.AddIndex(
            model_name='sanctionscheck',
            index=models.Index(fields=['match_status'], name='sanctions_s_match_s_d0860c_idx'),
        ),
        migrations.AddIndex(
            model_name='sanctionscheck',
            index=models.Index(fields=['check_date'], name='sanctions_s_check_d_841d22_idx'),
        ),
        migrations.AddIndex(
            model_name='sanctionsmatch',
            index=models.Index(fields=['sanctions_check', 'match_score'], name='sanctions_s_sanctio_0f3af1_idx'),
        ),
        migrations.AddIndex(
            model_name='sanctionsmatch',
            index=models.Index(fields=['review_status'], name='sanctions_s_review__364dc2_idx'),
        ),
    ]
