# Generated by Django 5.1.4 on 2025-07-07 10:02

import apps.documents.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('category', models.CharField(choices=[('IDENTIFICATION', 'Identificação'), ('ADDRESS_PROOF', 'Comprovante de Endereço'), ('INCOME_PROOF', 'Comprovante de Renda'), ('CORPORATE', 'Documentos Corporativos'), ('COMPLIANCE', 'Compliance'), ('OTHER', 'Outros')], max_length=20, verbose_name='Categoria')),
                ('is_required', models.BooleanField(default=False, verbose_name='Obrigatório')),
                ('allowed_extensions', models.CharField(default='pdf,jpg,jpeg,png,doc,docx', help_text='Extensões separadas por vírgula', max_length=200, verbose_name='Extensões Permitidas')),
                ('max_file_size_mb', models.IntegerField(default=10, verbose_name='Tamanho Máximo (MB)')),
                ('requires_approval', models.BooleanField(default=True, verbose_name='Requer Aprovação')),
                ('auto_approve', models.BooleanField(default=False, verbose_name='Aprovação Automática')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('file', models.FileField(upload_to=apps.documents.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'txt'])], verbose_name='Arquivo')),
                ('original_filename', models.CharField(max_length=500, verbose_name='Nome Original do Arquivo')),
                ('file_size', models.BigIntegerField(verbose_name='Tamanho do Arquivo (bytes)')),
                ('file_hash', models.CharField(blank=True, help_text='SHA-256 hash for integrity verification', max_length=64, verbose_name='Hash do Arquivo')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('UNDER_REVIEW', 'Em Análise'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado'), ('EXPIRED', 'Expirado'), ('REPLACED', 'Substituído')], default='PENDING', max_length=20, verbose_name='Status')),
                ('source', models.CharField(choices=[('UPLOAD', 'Upload Manual'), ('EMAIL', 'E-mail'), ('SCAN', 'Digitalização'), ('API', 'API'), ('IMPORT', 'Importação')], default='UPLOAD', max_length=20, verbose_name='Origem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Data de Expiração')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Revisado em')),
                ('review_notes', models.TextField(blank=True, verbose_name='Notas da Revisão')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo da Rejeição')),
                ('is_sensitive', models.BooleanField(default=False, verbose_name='Documento Sensível')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('version', models.IntegerField(default=1, verbose_name='Versão')),
                ('tags', models.CharField(blank=True, help_text='Tags separadas por vírgula', max_length=500, verbose_name='Tags')),
                ('beneficial_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customers.beneficialowner', verbose_name='Beneficiário Final')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case', verbose_name='Caso')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customers.customer', verbose_name='Cliente')),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='documents.document', verbose_name='Substituído por')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.documenttype', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('SUBMITTED', 'Enviado'), ('REVIEWED', 'Revisado'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado'), ('REQUESTED_CHANGES', 'Solicitadas Alterações'), ('RESUBMITTED', 'Reenviado')], max_length=20, verbose_name='Ação')),
                ('comments', models.TextField(blank=True, verbose_name='Comentários')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criada por')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_history', to='documents.document', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Revisão de Documento',
                'verbose_name_plural': 'Revisões de Documentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('template_type', models.CharField(choices=[('LETTER', 'Carta'), ('REPORT', 'Relatório'), ('FORM', 'Formulário'), ('CERTIFICATE', 'Certificado'), ('OTHER', 'Outro')], max_length=20, verbose_name='Tipo de Template')),
                ('content', models.TextField(help_text='Template content with placeholders like {{customer.name}}', verbose_name='Conteúdo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='Requer Aprovação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Template de Documento',
                'verbose_name_plural': 'Templates de Documentos',
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField(verbose_name='Número da Versão')),
                ('change_description', models.TextField(verbose_name='Descrição da Alteração')),
                ('file_path', models.CharField(max_length=500, verbose_name='Caminho do Arquivo')),
                ('file_size', models.BigIntegerField(verbose_name='Tamanho do Arquivo')),
                ('file_hash', models.CharField(max_length=64, verbose_name='Hash do Arquivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criada por')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Versão do Documento',
                'verbose_name_plural': 'Versões dos Documentos',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['customer', 'document_type'], name='documents_d_custome_299aa7_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='documents_d_status_07369e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_at'], name='documents_d_created_3b0a51_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['expiry_date'], name='documents_d_expiry__1d702a_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['file_hash'], name='documents_d_file_ha_a7f76e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version_number')},
        ),
    ]
