# Generated by Django 5.1.4 on 2025-07-07 10:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('rule_type', models.CharField(choices=[('KYC', 'Know Your Customer'), ('AML', 'Anti-Money Laundering'), ('SANCTIONS', 'Sanctions Screening'), ('PEP', 'Politically Exposed Persons'), ('FATCA', 'FATCA'), ('CRS', 'Common Reporting Standard'), ('OTHER', 'Outro')], max_length=20, verbose_name='Tipo de Regra')),
                ('severity', models.CharField(choices=[('LOW', 'Baixa'), ('MEDIUM', 'Média'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=10, verbose_name='Severidade')),
                ('auto_check', models.BooleanField(default=True, verbose_name='Verificação Automática')),
                ('requires_manual_review', models.BooleanField(default=False, verbose_name='Requer Revisão Manual')),
                ('condition_logic', models.TextField(blank=True, help_text='Descrição da lógica de verificação', verbose_name='Lógica da Condição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
            ],
            options={
                'verbose_name': 'Regra de Compliance',
                'verbose_name_plural': 'Regras de Compliance',
                'ordering': ['rule_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('report_type', models.CharField(choices=[('CUSTOMER_SUMMARY', 'Resumo do Cliente'), ('PERIODIC_REVIEW', 'Revisão Periódica'), ('REGULATORY_FILING', 'Arquivo Regulatório'), ('AUDIT_REPORT', 'Relatório de Auditoria'), ('EXCEPTION_REPORT', 'Relatório de Exceções')], max_length=20, verbose_name='Tipo de Relatório')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='Início do Período')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='Fim do Período')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('summary', models.TextField(blank=True, verbose_name='Resumo Executivo')),
                ('recommendations', models.TextField(blank=True, verbose_name='Recomendações')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('UNDER_REVIEW', 'Em Revisão'), ('APPROVED', 'Aprovado'), ('SUBMITTED', 'Enviado'), ('ARCHIVED', 'Arquivado')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_compliance_reports', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_compliance_reports', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_reports', to='customers.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Relatório de Compliance',
                'verbose_name_plural': 'Relatórios de Compliance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('metric_type', models.CharField(choices=[('COMPLETION_RATE', 'Taxa de Conclusão'), ('APPROVAL_RATE', 'Taxa de Aprovação'), ('AVERAGE_PROCESSING_TIME', 'Tempo Médio de Processamento'), ('EXCEPTION_RATE', 'Taxa de Exceções'), ('RISK_SCORE_DISTRIBUTION', 'Distribuição de Score de Risco')], max_length=30, verbose_name='Tipo de Métrica')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Alvo')),
                ('unit', models.CharField(default='%', max_length=50, verbose_name='Unidade')),
                ('period_start', models.DateField(verbose_name='Início do Período')),
                ('period_end', models.DateField(verbose_name='Fim do Período')),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Calculado em')),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Calculado por')),
            ],
            options={
                'verbose_name': 'Métrica de Compliance',
                'verbose_name_plural': 'Métricas de Compliance',
                'ordering': ['-calculated_at'],
                'unique_together': {('metric_type', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='ComplianceCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_status', models.CharField(choices=[('PENDING', 'Pendente'), ('IN_PROGRESS', 'Em Andamento'), ('PASSED', 'Aprovado'), ('FAILED', 'Reprovado'), ('REQUIRES_REVIEW', 'Requer Revisão'), ('EXEMPTED', 'Isento')], default='PENDING', max_length=20, verbose_name='Status da Verificação')),
                ('result_details', models.TextField(blank=True, verbose_name='Detalhes do Resultado')),
                ('risk_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Score de Risco')),
                ('check_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Verificação')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('next_check_date', models.DateTimeField(blank=True, null=True, verbose_name='Próxima Verificação')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_checks', to='customers.customer', verbose_name='Cliente')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_compliance_checks', to=settings.AUTH_USER_MODEL, verbose_name='Iniciado por')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_compliance_checks', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compliance.compliancerule', verbose_name='Regra')),
            ],
            options={
                'verbose_name': 'Verificação de Compliance',
                'verbose_name_plural': 'Verificações de Compliance',
                'ordering': ['-check_date'],
                'indexes': [models.Index(fields=['customer', 'check_status'], name='compliance__custome_745373_idx'), models.Index(fields=['rule', 'check_status'], name='compliance__rule_id_35a48e_idx'), models.Index(fields=['check_date'], name='compliance__check_d_e3c788_idx')],
                'unique_together': {('customer', 'rule', 'check_date')},
            },
        ),
        migrations.CreateModel(
            name='ComplianceAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('RULE_VIOLATION', 'Violação de Regra'), ('THRESHOLD_EXCEEDED', 'Limite Excedido'), ('REVIEW_DUE', 'Revisão Vencida'), ('DOCUMENT_EXPIRED', 'Documento Expirado'), ('SANCTIONS_MATCH', 'Correspondência de Sanções'), ('HIGH_RISK_ACTIVITY', 'Atividade de Alto Risco')], max_length=20, verbose_name='Tipo de Alerta')),
                ('severity', models.CharField(choices=[('INFO', 'Informativo'), ('WARNING', 'Aviso'), ('ERROR', 'Erro'), ('CRITICAL', 'Crítico')], default='WARNING', max_length=10, verbose_name='Severidade')),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('ACKNOWLEDGED', 'Reconhecido'), ('IN_PROGRESS', 'Em Andamento'), ('RESOLVED', 'Resolvido'), ('DISMISSED', 'Dispensado')], default='OPEN', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Reconhecido em')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Notas da Resolução')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Reconhecido por')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.case', verbose_name='Caso')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_alerts', to='customers.customer', verbose_name='Cliente')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Resolvido por')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compliance.compliancerule', verbose_name='Regra')),
            ],
            options={
                'verbose_name': 'Alerta de Compliance',
                'verbose_name_plural': 'Alertas de Compliance',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'severity'], name='compliance__status_7eec65_idx'), models.Index(fields=['customer'], name='compliance__custome_2ccc40_idx'), models.Index(fields=['created_at'], name='compliance__created_4811e7_idx')],
            },
        ),
    ]
